/**
 * Filename:
 * Description:
 * Copyright:   Copyright (c) 2013
 * Company:     Shanghai Huateng Software Systems Co., Ltd.
 * @author      Wubin
 * @version     1.0
 * Create at:   2016/4/21
 */
(function(){

	//跳转的路由配置
	var routeArry=[
		{
			'state':'list',
			'url':'/app_list',
			'default':'true',
			'templateUrl':'lnapp/app_list.html',
			'controller':'lnapplistController'
		},
		{
			'state':'add',
			'url':'/app_add',
			'default':'true',
			'templateUrl':'lnapp/app_add.html',
			'controller':'lnappaddController'
		},
		{
			'state':'lnapp',
			'url':'/lnapp',
			'default':'true',
			'templateUrl':'lnapp/app.html',
			'controller':'lnappController'
		},
		{
			'state':'lnapp.app',
			'url':'/lnappapp',
			'templateUrl':'lnapp/app_edit.html',
			'controller':'lnappeditController'
		},
		{
			'state':'lnapp.lcapp',
			'url':'/lnapplcapp',
			'templateUrl':'lnapp/app_lcedit.html',
			'controller':'lnappeditController'
		},
		{
			'state':'lnapp.ycapp',
			'url':'/lnappycapp',
			'templateUrl':'lnapp/app_ycedit.html',
			'controller':'lnappeditController'
		},
		{
			'state':'lnapp.gnty',
			'url':'/lnappgnty',
			'templateUrl':'gntycon/con_list.html',
			'controller':'gntyconlistController'
		},
		{
			'state':'lnapp.lginfo',
			'url':'/lnapplginfo',
			'templateUrl':'info/lg_edit.html',
			'controller':'infolistController'
		},
		{
			'state':'lnapp.eqptinfo',
			'url':'/lnappeqptinfo',
			'templateUrl':'info/eqpt_edit.html',
			'controller':'infolistController'
		},
		{
			'state':'lnapp.lcinfo',
			'url':'/lnapplcinfo',
			'templateUrl':'info/lc_edit.html',
			'controller':'infolistController'
		},
		{
			'state':'lnapp.billinfo',
			'url':'/lnappbillinfo',
			'templateUrl':'info/bill_list.html',
			'controller':'infolistController'
		},
		{
			'state':'lnapp.invinfo',
			'url':'/lnappinvinfo',
			'templateUrl':'info/inv_list.html',
			'controller':'infolistController'
		},
		{
			'state':'lnapp.bail',
			'url':'/bail',
			'templateUrl':'gntycon/bail_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lnapp.bailcash',
			'url':'/bailcash',
			'templateUrl':'gntycon/bailcash_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lnapp.mortgage',
			'url':'/mortgage',
			'templateUrl':'gntycon/mortgage_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lnapp.pledge',
			'url':'/pledge',
			'templateUrl':'gntycon/pledge_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lnapp.morthouse',
			'url':'/morthouse',
			'templateUrl':'gntyinfo/mort_house.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.mortland',
			'url':'/mortland',
			'templateUrl':'gntyinfo/mort_land.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.mortbuild',
			'url':'/mortbuild',
			'templateUrl':'gntyinfo/mort_build.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.morttraffic',
			'url':'/morttraffic',
			'templateUrl':'gntyinfo/mort_traffic.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.morteqpt',
			'url':'/morteqpt',
			'templateUrl':'gntyinfo/mort_eqpt.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.mortother',
			'url':'/mortother',
			'templateUrl':'gntyinfo/mort_other.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plbakdraft',
			'url':'/plbakdraft',
			'templateUrl':'gntyinfo/pledge_bakdraft.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plbbbond',
			'url':'/plbbbond',
			'templateUrl':'gntyinfo/pledge_budbusbond.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plcarcert',
			'url':'/plcarcert',
			'templateUrl':'gntyinfo/pledge_carcert.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plcert',
			'url':'/plcert',
			'templateUrl':'gntyinfo/pledge_cert.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.pldockwar',
			'url':'/pldockwar',
			'templateUrl':'gntyinfo/pledge_dockwar.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.pldraft',
			'url':'/pldraft',
			'templateUrl':'gntyinfo/pledge_draft.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plexport',
			'url':'/plexport',
			'templateUrl':'gntyinfo/pledge_export.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plforexchg',
			'url':'/plforexchg',
			'templateUrl':'gntyinfo/pledge_forexchg.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plfund',
			'url':'/plfund',
			'templateUrl':'gntyinfo/pledge_fund.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plgold',
			'url':'/plgold',
			'templateUrl':'gntyinfo/pledge_gold.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plgovbond',
			'url':'/plgovbond',
			'templateUrl':'gntyinfo/pledge_govbond.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plladbill',
			'url':'/',
			'templateUrl':'gntyinfo/pledge_ladbill.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.pllecrbak',
			'url':'/pllecrbak',
			'templateUrl':'gntyinfo/pledge_lecrbak.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.pllecred',
			'url':'/pllecred',
			'templateUrl':'gntyinfo/pledge_lecred.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plmisquote',
			'url':'/plmisquote',
			'templateUrl':'gntyinfo/pledge_misquote.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plmovable',
			'url':'/plmovable',
			'templateUrl':'gntyinfo/pledge_movable.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plother',
			'url':'/plother',
			'templateUrl':'gntyinfo/pledge_other.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plqutcriclt',
			'url':'/plqutcriclt',
			'templateUrl':'gntyinfo/pledge_quotecricult.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plqutown',
			'url':'/plqutown',
			'templateUrl':'gntyinfo/pledge_quoteown.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plrecvacct',
			'url':'/plrecvacct',
			'templateUrl':'gntyinfo/pledge_recvacct.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.pltraffic',
			'url':'/pltraffic',
			'templateUrl':'gntyinfo/pledge_traffic.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.pltransfer',
			'url':'/pltransfer',
			'templateUrl':'gntyinfo/pledge_transfer.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plwarnty',
			'url':'/plwarnty',
			'templateUrl':'gntyinfo/pledge_warnty.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lnapp.plstock',
			'url':'/plstock',
			'templateUrl':'gntyinfo/pledge_stock.html',
			'controller':'gntyinfoeditController'
		}
	]
	//模块的依赖加载配置
	var dependency=[
		//todo
	];
	scubeUI.module('bCrrLnAppService',dependency,routeArry);
}());
