/**
 * @author 	mengjiajia
 * @version 1.0
 * @Copyright Shanghai Huateng Software Systems Co., Ltd.
 * Create at:   2016/11/21
 */
(function(){

	//跳转的路由配置
	var routeArry=[
		{
			'state':'list',
			'url':'/con_list',
			'default':'true',
			'templateUrl':'lncon/con_list.html',
			'controller':'lnconlistController'
		},
		{
			'state':'lncon',
			'url':'/lncon',
			'default':'true',
			'templateUrl':'lncon/conn.html',
			'controller':'lnconController'
		},
		{
			'state':'lncon.con',
			'url':'/lnconcon',
			'templateUrl':'lncon/con_edit.html',
			'controller':'lnconeditController'
		},
		{
			'state':'lncon.lccon',
			'url':'/lnconlccon',
			'templateUrl':'lncon/con_lcedit.html',
			'controller':'lnconeditController'
		},
		{
			'state':'lncon.yccon',
			'url':'/lnconyccon',
			'templateUrl':'lncon/con_ycedit.html',
			'controller':'lnconeditController'
		},
		{
			'state':'lncon.gnty',
			'url':'/congnty',
			'templateUrl':'gntycon/con_list.html',
			'controller':'gntyconlistController'
		},
		{
			'state':'lncon.lginfo',
			'url':'/conlginfo',
			'templateUrl':'info/lg_edit.html',
			'controller':'infolistController'
		},
		{
			'state':'lncon.eqptinfo',
			'url':'/coneqptinfo',
			'templateUrl':'info/eqpt_edit.html',
			'controller':'infolistController'
		},
		{
			'state':'lncon.lcinfo',
			'url':'/conlcinfo',
			'templateUrl':'info/lc_edit.html',
			'controller':'infolistController'
		},
		{
			'state':'lncon.billinfo',
			'url':'/conbillinfo',
			'templateUrl':'info/bill_list.html',
			'controller':'infolistController'
		},
		{
			'state':'lncon.invinfo',
			'url':'/coninvinfo',
			'templateUrl':'info/inv_list.html',
			'controller':'infolistController'
		},
		{
			'state':'lncon.bail',
			'url':'/bail',
			'templateUrl':'gntycon/bail_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lncon.bailcash',
			'url':'/bailcash',
			'templateUrl':'gntycon/bailcash_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lncon.mortgage',
			'url':'/mortgage',
			'templateUrl':'gntycon/mortgage_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lncon.pledge',
			'url':'/pledge',
			'templateUrl':'gntycon/pledge_edit.html',
			'controller':'gntyconeditController'
		},
		{
			'state':'lncon.morthouse',
			'url':'/morthouse',
			'templateUrl':'gntyinfo/mort_house.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.mortland',
			'url':'/mortland',
			'templateUrl':'gntyinfo/mort_land.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.mortbuild',
			'url':'/mortbuild',
			'templateUrl':'gntyinfo/mort_build.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.morttraffic',
			'url':'/morttraffic',
			'templateUrl':'gntyinfo/mort_traffic.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.morteqpt',
			'url':'/morteqpt',
			'templateUrl':'gntyinfo/mort_eqpt.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.mortother',
			'url':'/mortother',
			'templateUrl':'gntyinfo/mort_other.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plbakdraft',
			'url':'/plbakdraft',
			'templateUrl':'gntyinfo/pledge_bakdraft.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plbbbond',
			'url':'/plbbbond',
			'templateUrl':'gntyinfo/pledge_budbusbond.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plcarcert',
			'url':'/plcarcert',
			'templateUrl':'gntyinfo/pledge_carcert.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plcert',
			'url':'/plcert',
			'templateUrl':'gntyinfo/pledge_cert.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.pldockwar',
			'url':'/pldockwar',
			'templateUrl':'gntyinfo/pledge_dockwar.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.pldraft',
			'url':'/pldraft',
			'templateUrl':'gntyinfo/pledge_draft.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plexport',
			'url':'/plexport',
			'templateUrl':'gntyinfo/pledge_export.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plforexchg',
			'url':'/plforexchg',
			'templateUrl':'gntyinfo/pledge_forexchg.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plfund',
			'url':'/plfund',
			'templateUrl':'gntyinfo/pledge_fund.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plgold',
			'url':'/plgold',
			'templateUrl':'gntyinfo/pledge_gold.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plgovbond',
			'url':'/plgovbond',
			'templateUrl':'gntyinfo/pledge_govbond.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plladbill',
			'url':'/',
			'templateUrl':'gntyinfo/pledge_ladbill.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.pllecrbak',
			'url':'/pllecrbak',
			'templateUrl':'gntyinfo/pledge_lecrbak.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.pllecred',
			'url':'/pllecred',
			'templateUrl':'gntyinfo/pledge_lecred.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plmisquote',
			'url':'/plmisquote',
			'templateUrl':'gntyinfo/pledge_misquote.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plmovable',
			'url':'/plmovable',
			'templateUrl':'gntyinfo/pledge_movable.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plother',
			'url':'/plother',
			'templateUrl':'gntyinfo/pledge_other.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plqutcriclt',
			'url':'/plqutcriclt',
			'templateUrl':'gntyinfo/pledge_quotecricult.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plqutown',
			'url':'/plqutown',
			'templateUrl':'gntyinfo/pledge_quoteown.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plrecvacct',
			'url':'/plrecvacct',
			'templateUrl':'gntyinfo/pledge_recvacct.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.pltraffic',
			'url':'/pltraffic',
			'templateUrl':'gntyinfo/pledge_traffic.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.pltransfer',
			'url':'/pltransfer',
			'templateUrl':'gntyinfo/pledge_transfer.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plwarnty',
			'url':'/plwarnty',
			'templateUrl':'gntyinfo/pledge_warnty.html',
			'controller':'gntyinfoeditController'
		},
		{
			'state':'lncon.plstock',
			'url':'/plstock',
			'templateUrl':'gntyinfo/pledge_stock.html',
			'controller':'gntyinfoeditController'
		}
	]
	//模块的依赖加载配置
	var dependency=[
		//todo
	];
	scubeUI.module('bCrrLnConService',dependency,routeArry);
}());
