/**
 * @author 	mengjiajia
 * @version 1.0
 * @Copyright Shanghai Huateng Software Systems Co., Ltd.
 * Create at:   2016/11/21
 */
(function(){
	var parentwindow = window.parent;
    window.userInfo = parentwindow.userInfo;
    window.authorization=parentwindow.authorization;
    window.httpIpPort = parentwindow.httpIpPort;
    window.dictionary = parentwindow.dictionary;
    window._HTTP_IP_PORT = parentwindow._HTTP_IP_PORT;
    window.appNo = parentwindow.appNo;

    //跳转的路由配置
    var routeArry=[
        {
            'state':'app',
            'url':'/app',
            'templateUrl':'lnapp/app_edit.html',
            'controller':'lnappeditController'
        },
        {
            'state':'lcapp',
            'url':'/lcapp',
            'templateUrl':'lnapp/app_lcedit.html',
            'controller':'lnappeditController'
        },
        {
            'state':'ycapp',
            'url':'/ycapp',
            'templateUrl':'lnapp/app_ycedit.html',
            'controller':'lnappeditController'
        },
        {
            'state':'appguide',
            'templateUrl':'lnappguide_mdle.html'
        },
        {
            'state':'gnty',
            'url':'/appgnty',
            'templateUrl':'gntycon/con_list.html',
            'controller':'gntyconlistController'
        },
        {
            'state':'lginfo',
            'url':'/applginfo',
            'templateUrl':'info/lg_edit.html',
            'controller':'infolistController'
        },
        {
            'state':'eqptinfo',
            'url':'/appeqptinfo',
            'templateUrl':'info/eqpt_edit.html',
            'controller':'infolistController'
        },
        {
            'state':'lcinfo',
            'url':'/applcinfo',
            'templateUrl':'info/lc_edit.html',
            'controller':'infolistController'
        },
        {
            'state':'billinfo',
            'url':'/appbillinfo',
            'templateUrl':'info/bill_list.html',
            'controller':'infolistController'
        },
        {
            'state':'invinfo',
            'url':'/appinvinfo',
            'templateUrl':'info/inv_list.html',
            'controller':'infolistController'
        },
        {
            'state':'bail',
            'url':'/bail',
            'templateUrl':'gntycon/bail_edit.html',
            'controller':'gntyconeditController'
        },
        {
            'state':'bailcash',
            'url':'/bailcash',
            'templateUrl':'gntycon/bailcash_edit.html',
            'controller':'gntyconeditController'
        },
        {
            'state':'mortgage',
            'url':'/mortgage',
            'templateUrl':'gntycon/mortgage_edit.html',
            'controller':'gntyconeditController'
        },
        {
            'state':'pledge',
            'url':'/pledge',
            'templateUrl':'gntycon/pledge_edit.html',
            'controller':'gntyconeditController'
        },
        {
            'state':'morthouse',
            'url':'/morthouse',
            'templateUrl':'gntyinfo/mort_house.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'mortland',
            'url':'/mortland',
            'templateUrl':'gntyinfo/mort_land.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'mortbuild',
            'url':'/mortbuild',
            'templateUrl':'gntyinfo/mort_build.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'morttraffic',
            'url':'/morttraffic',
            'templateUrl':'gntyinfo/mort_traffic.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'morteqpt',
            'url':'/morteqpt',
            'templateUrl':'gntyinfo/mort_eqpt.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'mortother',
            'url':'/mortother',
            'templateUrl':'gntyinfo/mort_other.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plbakdraft',
            'url':'/plbakdraft',
            'templateUrl':'gntyinfo/pledge_bakdraft.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plbbbond',
            'url':'/plbbbond',
            'templateUrl':'gntyinfo/pledge_budbusbond.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plcarcert',
            'url':'/plcarcert',
            'templateUrl':'gntyinfo/pledge_carcert.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plcert',
            'url':'/plcert',
            'templateUrl':'gntyinfo/pledge_cert.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'pldockwar',
            'url':'/pldockwar',
            'templateUrl':'gntyinfo/pledge_dockwar.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'pldraft',
            'url':'/pldraft',
            'templateUrl':'gntyinfo/pledge_draft.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plexport',
            'url':'/plexport',
            'templateUrl':'gntyinfo/pledge_export.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plforexchg',
            'url':'/plforexchg',
            'templateUrl':'gntyinfo/pledge_forexchg.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plfund',
            'url':'/plfund',
            'templateUrl':'gntyinfo/pledge_fund.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plgold',
            'url':'/plgold',
            'templateUrl':'gntyinfo/pledge_gold.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plgovbond',
            'url':'/plgovbond',
            'templateUrl':'gntyinfo/pledge_govbond.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plladbill',
            'url':'/',
            'templateUrl':'gntyinfo/pledge_ladbill.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'pllecrbak',
            'url':'/pllecrbak',
            'templateUrl':'gntyinfo/pledge_lecrbak.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'pllecred',
            'url':'/pllecred',
            'templateUrl':'gntyinfo/pledge_lecred.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plmisquote',
            'url':'/plmisquote',
            'templateUrl':'gntyinfo/pledge_misquote.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plmovable',
            'url':'/plmovable',
            'templateUrl':'gntyinfo/pledge_movable.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plother',
            'url':'/plother',
            'templateUrl':'gntyinfo/pledge_other.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plqutcriclt',
            'url':'/plqutcriclt',
            'templateUrl':'gntyinfo/pledge_quotecricult.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plqutown',
            'url':'/plqutown',
            'templateUrl':'gntyinfo/pledge_quoteown.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plrecvacct',
            'url':'/plrecvacct',
            'templateUrl':'gntyinfo/pledge_recvacct.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'pltraffic',
            'url':'/pltraffic',
            'templateUrl':'gntyinfo/pledge_traffic.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'pltransfer',
            'url':'/pltransfer',
            'templateUrl':'gntyinfo/pledge_transfer.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plwarnty',
            'url':'/plwarnty',
            'templateUrl':'gntyinfo/pledge_warnty.html',
            'controller':'gntyinfoeditController'
        },
        {
            'state':'plstock',
            'url':'/plstock',
            'templateUrl':'gntyinfo/pledge_stock.html',
            'controller':'gntyinfoeditController'
        }
    ];
    //模块的依赖加载配置
    var dependency=[
        //todo
    ];

  scubeUI.module('lnappguideMdle',dependency,routeArry);
  //手动拉起angular应用程序
  angular.element(document).ready(function() {
      angular.bootstrap(document.getElementsByTagName("body"),[scubeUI.moduleName]);
  });
        
}());
