/**
 * Created by huangshuidan on 2016/11/11.
 */
(function(){
    //跳转的路由配置
    var routeArry=[
        {
            'state':'bsystask',
            'url':'/bsystask',
            'default':'true',
            'templateUrl':'bsystask/bsys_task.html',
            'controller':'bsysTaskController'
        },
        {
            'state':'bsystaskmain',
            'url':'/bsystaskmain',
            'templateUrl':'bsystask/bsys_task_main.html',
            'controller':'bsysTaskMainController'
        },
        {
            'state':'bsystasktab',
            'url':'/bsystasktab/:appNo/:pageUrl/:taskId/:processId/:custId/:custNm/:modelId/:nodeButton',
            'templateUrl':'bsystask/bsys_tasktab.html',
            'controller':'bsysTaskTabController'          
        },
        {
            'state':'bsystasktab.bdcrview',
            'url':'/bsystasktab.bdcrview',
            'templateUrl':'../../bas_dcr_mdle/html/app/addguide.html'
        },
        
        {
            'state':'bsystasktab.commentview',
            'url':'/bsystasktab.commentview',
            'templateUrl':'bsysapplydtl/bsys_taskcomment.html',
            'controller':'bsysTaskCommentController'
        } ,
        {
            'state':'bsystasktab.lnapp',
            'url':'/bsystasktab.lnapp',
            'templateUrl':'../../bas_crr_mdle/html/lnapp/app_guide.html'
        },
        //先票/款后货放款
        {
            'state':'bsystasktab.repayFourWare',
            'url':'/bsystasktab.repayFourWare',
            'templateUrl':'../../bas_lan_mdle/html/repay_fourWare.html'
        },
        //流贷
        {
            'state':'bsystasktab.repayFourWareLiuDai',
            'url':'/bsystasktab.repayFourWareLiuDai',
            'templateUrl':'../../bas_lan_mdle/html/repay_fourWare_liuDai.html'
        },
        {
            'state':'bsystasktab.repay',
            'url':'/bsystasktab.repay',
            'templateUrl':'../../bas_lan_mdle/html/repay.html'
        },
        {
            'state':'bsystasktab.duebillappview',
            'url':'/bsystasktab.duebillappview',
            'templateUrl':'../../bas_crr_mdle/html/duebill/duebillapp_guide.html'
        },
        {
            'state':'bsystasktab.evalapprview',
            'url':'/bsystasktab.evalapprview',
            'templateUrl':'../../bas_crg_mdle/html/eval/crgeval_appr.html',
            'controller':'EvalApprController'
        },
        {
            'state':'bsystasktab.ThreeAccountConfirmApplyview',
            'url':'/bsystasktab.ThreeAccountConfirmApplyview',
            'templateUrl':'../../adv_tcs_mdle/html/atcsthreeConfirm/threeConfirmAppGuide.html'
        }
        ,{
            'state':'bsystasktab.ThreeGuaBuybackApplyview',
            'url':'/bsystasktab.ThreeGuaBuybackApplyview',
            'templateUrl':'../../adv_tcs_mdle/html/atcsthreeGuaBuyback/threeGuaBuybackAppGuide.html'
        },
      	{
            'state':'bsystasktab.ThreeDeliveryApplyview',
            'url':'/bsystasktab.ThreeDeliveryApplyview',
            'templateUrl':'../../adv_tcs_mdle/html/atcsthreeDelivery/threeDeliveryAppGuide.html'
        },
        
        //先票/款后货begin
        //收款确认
        {
            'state':'bsystasktab.FourAccountConfirmApplyview',
            'url':'/bsystasktab.FourAccountConfirmApplyview',
            'templateUrl':'../../adv_bcp_mdle/html/abcpfourConfirm/fourConfirmAppGuide.html'
        },
        //出质入库
        {
            'state':'bsystasktab.FourhousePledgeApply',
            'url':'/bsystasktab.FourhousePledgeApply',
            'templateUrl':'../../adv_fcs_mdle/html/afcsfourPledge/fourPledgeAppGuide.html'
        },
        //现货静态/动态出质入库
        {
            'state':'bsystasktab.StaticQualityApply',
            'url':'/bsystasktab.StaticQualityApply',
            'templateUrl':'../../sto_smp_mdle/html/qualityApply/sto_qualityApplyGuide.html'
        },
        //现货动态出质入库
        {
            'state':'bsystasktab.DynamicQualityApply',
            'url':'/bsystasktab.DynamicQualityApply',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApplyXhdt/sto_qualityApplyGuide.html'
        },
        //提货申请（一一对应）
        {
            'state':'bsystasktab.One2OneFourDeliveryApply',
            'url':'/bsystasktab.One2OneFourDeliveryApply',
            'templateUrl':'../../adv_fcs_mdle/html/afcsfourDelivery/fourDeliveryAppGuide.html'
        },
        //差额退款
        {
            'state':'bsystasktab.FourGuaBuybackApply',
            'url':'/bsystasktab.FourGuaBuybackApply',
            'templateUrl':'../../adv_fcs_mdle/html/afcsfourGuaBuyback/fourGuaBuybackAppGuide.html'
        },
        //先票/款后货end
        {
            'state':'bsystasktab.recdisptregview',
            'url':'/bsystasktab.recdisptregview',
            'templateUrl':'../../rec_bcp_mdle/html/dsptreg/dsptRegViewSbmt.html',
            'controller':'dsptRegViewController'
        },
        {
            'state':'bsystasktab.recdisptregapprview',
            'url':'/bsystasktab.recdisptregapprview',
            'templateUrl':'../../rec_bcp_mdle/html/dsptreg/dsptRegViewAppr.html',
            'controller':'dsptRegViewApprController'
        },
        {
            'state':'bsystasktab.lowerprice',
            'url':'/bsystasktab.lowerprice',
            'templateUrl':'../../sto_dmp_mdle/html/lowerprice/lowerprice_guide.html'
        }
        ,{
            'state':'bsystasktab.confirmTransfer',
            'url':'/bsystasktab.confirmTransfer',
            'templateUrl':'../../rec_bcp_mdle/html/appli/tansferConfirm.html'
        }
        ,{
            'state':'bsystasktab.checkTransfer',
            'url':'/bsystasktab.checkTransfer',
            'templateUrl':'../../rec_bcp_mdle/html/appli/checkTransfer.html'
        }
        ,{
            'state':'bsystasktab.checkTransferAgain',
            'url':'/bsystasktab.checkTransferAgain',
            'templateUrl':'../../rec_bcp_mdle/html/appli/checkTransfer.html'
        }
        ,{
            'state':'bsystasktab.writeoffTask',
            'url':'/bsystasktab.writeoffTask',
            'templateUrl':'../../rec_bcp_mdle/html/writeoff/writeoffTask.html'
        },
        {
            'state':'bsystasktab.writeoffPoolTask',
            'url':'/bsystasktab.writeoffPoolTask',
            'templateUrl':'../../rec_bcp_mdle/html/writeoffPool/writeoffPoolTask.html'
        },
        {
            'state':'bsystasktab.qualityApplyWrite',
            'url':'/bsystasktab.qualityApplyWrite',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyWrite_task.html',
            'controller':'qualityApplyController'
        },
        {
            'state':'bsystasktab.qualityApplyWrite.qualityInfo',
            'url':'/qualityInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyInfoWrite.html',
            'controller':'qualityApplyInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyWrite.gntyconInfo',
            'url':'/gntyconInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/gntyconInfo.html',
            'controller':'gntyconInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyWrite.mortgageInfo',
            'url':'/mortgageInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/mortgageInfo.html',
            'controller':'mortgageInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyWrite.custInfo',
            'url':'/custInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/custInfo.html',
            'controller':'custInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyCheck',
            'url':'/bsystasktab.qualityApplyCheck',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyCheck_task.html',
            'controller':'qualityApplyController'
        },
        {
            'state':'bsystasktab.qualityApplyCheck.qualityInfo',
            'url':'/qualityInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyInfoCheck.html',
            'controller':'qualityApplyInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyCheck.gntyconInfo',
            'url':'/gntyconInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/gntyconInfo.html',
            'controller':'gntyconInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyCheck.mortgageInfo',
            'url':'/mortgageInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/mortgageInfo.html',
            'controller':'mortgageInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyCheck.custInfo',
            'url':'/custInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/custInfo.html',
            'controller':'custInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyApprove',
            'url':'/bsystasktab.qualityApplyApprove',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyApprove_task.html',
            'controller':'qualityApplyController'
        },
        {
            'state':'bsystasktab.qualityApplyApprove.qualityInfo',
            'url':'/qualityInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyInfoApprove.html',
            'controller':'qualityApplyInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyApprove.gntyconInfo',
            'url':'/gntyconInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/gntyconInfo.html',
            'controller':'gntyconInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyApprove.mortgageInfo',
            'url':'/mortgageInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/mortgageInfo.html',
            'controller':'mortgageInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyApprove.custInfo',
            'url':'/custInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/custInfo.html',
            'controller':'custInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyReceipt',
            'url':'/bsystasktab.qualityApplyReceipt',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyReceipt_task.html',
            'controller':'qualityApplyController'
        },
        {
            'state':'bsystasktab.qualityApplyReceipt.qualityInfo',
            'url':'/qualityInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/qualityApplyInfoReceipt.html',
            'controller':'qualityApplyInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyReceipt.gntyconInfo',
            'url':'/gntyconInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/gntyconInfo.html',
            'controller':'gntyconInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyReceipt.mortgageInfo',
            'url':'/mortgageInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/mortgageInfo.html',
            'controller':'mortgageInfoController'
        },
        {
            'state':'bsystasktab.qualityApplyReceipt.custInfo',
            'url':'/custInfo',
            'templateUrl':'../../bas_pbc_mdle/html/qualityApply/custInfo.html',
            'controller':'custInfoController'
        },
        {
            'state':'bsystasktab.payment',
            'url':'/payment',
            'templateUrl':'../../rec_bcp_mdle/html/payment/payment_update.html',
            'controller':'paymentUpdateController'
        },
        {
            'state':'bsystasktab.pooldisputeSubmit',
            'url':'/pooldisputeSubmit',
            'templateUrl':'../../rec_bcp_mdle/html/pooldsptreg/pooldsptRegViewSbmt.html',
            'controller':'pooldsptRegSbmtViewController'
        },
        {
            'state':'bsystasktab.pooldisputeApprove',
            'url':'/pooldisputeApprove',
            'templateUrl':'../../rec_bcp_mdle/html/pooldsptreg/pooldsptRegViewAppr.html',
            'controller':'pooldsptRegApprViewController'
        },
        {
            'state':'bsystasktab.debtPress',
            'url':'/debtPress',
            'templateUrl':'../../rec_bcp_mdle/html/debtPress/debtPressDtlApp.html'
        },
        {
            'state':'bsystasktab.debtPoolPress',
            'url':'/debtPoolPress',
            //'templateUrl':'../../rec_bcp_mdle/html/debtPoolPress/debtPoolPressDtl.html',
           // 'controller':'debtPoolPressDtlController'
            'templateUrl':'../../rec_bcp_mdle/html/debtPoolPress/debtPoolPressDtlApp.html'
        },
        {
            'state':'bsystasktab.debtOutPool',
            'url':'/debtOutPool',
            //'templateUrl':'../../rec_bcp_mdle/html/debtOutPool/debtOutPoolDtl.html',
           // 'controller':'debtOutPoolDtlController'
            'templateUrl':'../../rec_bcp_mdle/html/debtOutPool/debtOutPoolDtlApp.html'
        },
        {
            'state':'bsystasktab.backtransfer',
            'url':'/backtransfer',
            'templateUrl':'../../rec_bcp_mdle/html/backtransfer/backtransfer_guide.html'
        },
        {
            'state':'bsystasktab.backtransferpool',
            'url':'/backtransfer',
            'templateUrl':'../../rec_bcp_mdle/html/backtransfer/backtransfer_guide.html'
        },
        {
            'state':'bsystasktab.poolRePayWrite',
            'url':'/poolRePayWrite',
            'templateUrl':'../../rec_bcp_mdle/html/poolRePay/poolRePayMain.html',
            'controller':'poolRePayMainController'
        },
        {
            'state':'bsystasktab.poolRePayCheck',
            'url':'/poolRePayCheck',
            'templateUrl':'../../rec_bcp_mdle/html/poolRePay/poolRePayTask.html',
            'controller':'poolRePayMainController'
        },
        {
            'state':'bsystasktab.rePayWrite',
            'url':'/rePayWrite',
            'templateUrl':'../../rec_bcp_mdle/html/poolRePay/poolRePayMain.html',
            'controller':'rePayMainController'
        },
        {
            'state':'bsystasktab.rePayCheck',
            'url':'/rePayCheck',
            'templateUrl':'../../rec_bcp_mdle/html/poolRePay/poolRePayTask.html',
            'controller':'rePayMainController'
        },
        {
            'state':'bsystasktab.CashPaymentApply',
            'url':'/CashPaymentApply',
            'templateUrl':'../../rec_bcp_mdle/html/payment/payment_update.html',
            'controller':'paymentUpdateController'
        },
        {
            'state':'bsystasktab.FactoringPoolPaymentApply',
            'url':'/factoringPoolPaymentApply',
            'templateUrl':'../../rec_bcp_mdle/html/paymentpool/paymentpool_update.html',
            'controller':'paymentPoolUpdateController'
        },
        {
            'state':'bsystasktab.debtInPool',
            'url':'/debtInPool',
            'templateUrl':'../../rec_bcp_mdle/html/debtInPool/debtInPool_guide.html'
        }
        ,
        {
            'state':'bsystasktab.pooldsptInvAdd',
            'url':'/pooldsptInvAdd',
            'templateUrl':'../../rec_bcp_mdle/html/pooldsptreg/pooldsptInvAdd.html',
            'controller':'pooldsptInvAddController'
        },
        {
            'state':'bsystasktab.pooldisputeSave',
            'url':'/pooldisputeSubmit',
            'templateUrl':'../../rec_bcp_mdle/html/pooldsptreg/pooldsptRegViewSbmt.html',
            'controller':'pooldsptRegSbmtViewController'
        },
        {
            'state':'bsystasktab.disputePoolRW',
            'url':'/bsystasktab.disputePoolRW',
            'templateUrl':'../../rec_bcp_mdle/html/appli/poolDisputeRemove.html'
        },
        {
            'state':'bsystasktab.disputeRW',
            'url':'/bsystasktab.disputeRW',
            'templateUrl':'../../rec_bcp_mdle/html/appli/disputeRemove.html'
        },
        {
            'state':'bsystasktab.AllowancePoolApply',
            'url':'/bsystasktab.AllowancePoolApply',
            'templateUrl':'../../rec_bcp_mdle/html/poolImpairment/poolimpairAdd_apply.html',
            'controller':'dsptRemAddController'
        },
        {
            'state':'bsystasktab.AllowanceApply',
            'url':'/bsystasktab.AllowanceApply',
            'templateUrl':'../../rec_bcp_mdle/html/impairment/impairAdd.html',
            'controller':'impairAddController'
        },
        {
            'state':'bsystasktab.cashEqualValue',
            'url':'/bsystasktab.cashEqualValue',
            'templateUrl':'../../bas_mrn_mdle/html/cashEqualValueRegister/register_guide.html'
        },
        {
            'state':'bsystasktab.lncimarginapply',
            'url':'/bsystasktab.lncimarginapply',
            'templateUrl':'../../bas_mrn_mdle/html/lncimargin/lncimarginapplytask.html',
            'controller':'lncimarginapplyController'
        },
        {
            'state':'bsystasktab.dismortgageBill',
            'url':'/bsystasktab.dismortgageBill',
            'templateUrl':'../../bas_mrn_mdle/html/dismortgageBill/bill_guide.html'
        },
        {
            'state':'bsystasktab.transferOutApply',
            'url':'/bsystasktab.transferOutApply',
            'templateUrl':'../../bas_mrn_mdle/html/maximumbail/transferOutApply_guide.html'
        },
        {
            'state':'bsystasktab.billnormalPledge',
            'url':'/bsystasktab.billnormalPledge',
            'templateUrl':'../../sto_nwr_mdle/html/pledgemng/pledge_mng_guide.html'
        },
        //普通仓单放款----------------------------------------------------------------------开始
        {
            'state':'bsystasktab.repayBillNormalCash',
            'url':'/bsystasktab.repayBillNormalCash',
            'templateUrl':'../../bas_lan_mdle/html/billnormal/repay_billnormal_cashguide.html'
        },
        {
            'state':'bsystasktab.repayBillNormalBill',
            'url':'/bsystasktab.repayBillNormalBill',
            'templateUrl':'../../bas_lan_mdle/html/billnormal/repay_billnormal_billguide.html'
        },
        //普通仓单放款----------------------------------------------------------------------结束
        {
            'state':'bsystasktab.multiPriceAdjustApply',
            'url':'/bsystasktab.multiPriceAdjustApply',
            'templateUrl':'../../adv_fcs_mdle/html/multiPriceAdjust/multiPriceAdjust_Apply_Info.html',
            'controller':'multiPriceAdjustController'
        },
        //现货静态批量调价
        {
            'state':'bsystasktab.multiPriceAdjustApplyXhjt',
            'url':'/bsystasktab.multiPriceAdjustApplyXhjt',
            'templateUrl':'../../sto_smp_mdle/html/multiPriceAdjust/multiPriceAdjust_Apply_Info.html',
            'controller':'multiPriceAdjustControllerXhjt'
        },
        //现货动态批量调价
        {
            'state':'bsystasktab.multiPriceAdjustApplyXhdt',
            'url':'/bsystasktab.multiPriceAdjustApplyXhdt',
            'templateUrl':'../../sto_dmp_mdle/html/multiPriceAdjust/multiPriceAdjust_Apply_Info.html',
            'controller':'multiPriceAdjustControllerXhdt'
        },
        {
            'state':'bsystasktab.billnormalDelivery',
            'url':'/bsystasktab.billnormalDelivery',
            'templateUrl':'../../sto_nwr_mdle/html/delivery/delivery_guide.html'
        },
        {//普通仓单追加申请
            'state':'bsystasktab.billnormalAdd',
            'url':'/bsystasktab.billnormalAdd',
            'templateUrl':'../../sto_nwr_mdle/html/billnormaladd/billnormal_add_guide.html'
        },
        {//非标仓单解押
            'state':'bsystasktab.billnormalUnPledge',
            'url':'/bsystasktab.billnormalUnPledge',
            'templateUrl':'../../sto_nwr_mdle/html/offmng/off_mng_guide.html'
        },
        //现货静态价格调整
        {
            'state':'bsystasktab.adjustPriceApply',
            'url':'/bsystasktab.adjustPriceApply',
            'templateUrl':'../../sto_pbc_mdle/html/priceadjust/adjustPriceAppGuide.html'
        },
        //现货动态价格调整
        {
            'state':'bsystasktab.adjustPriceApplyXhdt',
            'url':'/bsystasktab.adjustPriceApplyXhdt',
            'templateUrl':'../../sto_dmp_mdle/html/priceadjust/adjustPriceAppGuide.html'
        },
        //先票款后货价格调整
        {
            'state':'bsystasktab.adjustPriceApplyXphh',
            'url':'/bsystasktab.adjustPriceApplyXphh',
            'templateUrl':'../../adv_fcs_mdle/html/fourpriceadjust/adjustPriceAppGuide.html'
        },
        {//非标仓单置换
            'state':'bsystasktab.billnormalMngExcg',
            'url':'/bsystasktab.billnormalMngExcg',
            'templateUrl':'../../sto_nwr_mdle/html/mngexcg/mng_excg_guide.html'
        },
        //非标仓单价格调整
        {
            'state':'bsystasktab.adjustPriceApplicationBill',
            'url':'/bsystasktab.adjustPriceApplicationBill',
            'templateUrl':'../../sto_nwr_mdle/html/adjustpricebill/adjustPriceAppGuide.html'
        },
        {//现货静态放款审批、现货动态放款审批    流贷
            'state':'bsystasktab.repayCashMtg',
            'url':'/bsystasktab.repayCashMtg',
            'templateUrl':'../../bas_lan_mdle/html/staticmtg/repay_cashmtg_guide.html'
        },
        {//现货静态放款审批、现货动态放款审批    银承
            'state':'bsystasktab.repayBillMtg',
            'url':'/bsystasktab.repayBillMtg',
            'templateUrl':'../../bas_lan_mdle/html/staticmtg/repay_billmtg_guide.html'
        },
        {//现货静态提货申请
            'state':'bsystasktab.staticDeliveryApply',
            'url':'/bsystasktab.staticDeliveryApply',
            'templateUrl':'../../sto_smp_mdle/html/deliveryApply/delivery_apply_guide.html'
        },
        {//应收类业务申请
            'state':'bsystasktab.factoringApply',
            'url':'/bsystasktab.factoringApply',
            'templateUrl':'../../nrec_bcp_mdle/html/busapply/bcp_apply_guide.html'

        },
        {//应收账款转让
            'state':'bsystasktab.Ntransfer',
            'url':'/bsystasktab.Ntransfer',
            'templateUrl':'../../nrec_bcp_mdle/html/debtTransfer/debt_transfer.html',
            'controller':'nRDebtTransferController'
        },
        {//应收账款融资流贷放款
            'state':'bsystasktab.invoiceFinancingCash',
            'url':'/bsystasktab.invoiceFinancingCash',
            'templateUrl':'../../nrec_bcp_mdle/html/lanlnci/bcp_lan_edit.html',
            'controller':'nrBcpLanEditController'
        },
        {//应收账款池融资流贷放款
            'state':'bsystasktab.financingPoolCash',
            'url':'/bsystasktab.financingPoolCash',
            'templateUrl':'../../nrec_bcp_mdle/html/lanlnci/bcp_lan_pooledit.html',
            'controller':'nrBcpLanPoolEditController'
        },
        {//应收账款融资催收申请
            'state':'bsystasktab.debtPressingApply',
            'url':'/bsystasktab.debtPressingApply',
            'templateUrl':'../../nrec_bcp_mdle/html/debtPress/bcp_press_edit.html',
            'controller':'nrecBcpPressEditController'

        },
        {//应收账款商纠登记申请
            'state':'bsystasktab.NdisputeRegister',
            'url':'/bsystasktab.NdisputeRegister',
            'templateUrl':'../../nrec_bcp_mdle/html/disputeRegister/disputeRegister_guide.html'
           /* 'controller':'dRegisterApplyController'*/
        },
        {//应收账款商纠登记解除申请
            'state':'bsystasktab.NdisputeRemove',
            'url':'/bsystasktab.NdisputeRemove',
            'templateUrl':'../../nrec_bcp_mdle/html/disputeRemove/disputeRemove_guide.html'
           /* 'controller':'dRemoveApplyController'*/
        },
        {//应收账款融资反转让申请
            'state':'bsystasktab.debtBackTransferApply',
            'url':'/bsystasktab.debtBackTransferApply',
            'templateUrl':'../../nrec_bcp_mdle/html/backTransfer/bcp_backtransfer_guide.html'
        },
        {//应收账款池融资反转让申请
            'state':'bsystasktab.debtPoolBackTransferApply',
            'url':'/bsystasktab.debtPoolBackTransferApply',
            'templateUrl':'../../nrec_bcp_mdle/html/backTransfer/bcp_backtransfer_guide.html'
        },
		{//应收账款融资核销申请
            'state':'bsystasktab.debtCancelApply',
            'url':'/bsystasktab.debtCancelApply',
            'templateUrl':'../../nrec_bcp_mdle/html/chargeOff/bcp_chargeoff_edit.html',
            'controller':'nrecBcpChargeOffEditController'
        },
        {//应收账款池融资核销申请
            'state':'bsystasktab.debtPoolCancelApply',
            'url':'/bsystasktab.debtPoolCancelApply',
            'templateUrl':'../../nrec_bcp_mdle/html/chargeOff/bcp_chargeoff_edit.html',
            'controller':'nrecBcpChargeOffEditController'
        },
        {//应收账款现金回款处理
            'state':'bsystasktab.nCashPaymentApply',
            'url':'/bsystasktab.nCashPaymentApply',
            'templateUrl':'../../nrec_bcp_mdle/html/repayment/cashpayment/payment_apply.html',
            'controller':'paymentApplyController'
        },
        {//应收账款池融资现金回款处理
            'state':'bsystasktab.nFactoringPoolPaymentApply',
            'url':'/bsystasktab.nFactoringPoolPaymentApply',
            'templateUrl':'../../nrec_bcp_mdle/html/repayment/cashpayment/payment_update.html',
            'controller':'paymentUpdateController'
        },
        {//应收账款融资减值申请
            'state':'bsystasktab.debtImpairmentApply',
            'url':'/bsystasktab.debtImpairmentApply',
            'templateUrl':'../../nrec_bcp_mdle/html/debtImpairment/bcp_impairment_guide.html'
        },
        {//应收账款池融资减值申请
            'state':'bsystasktab.debtPoolImpairmentApply',
            'url':'/bsystasktab.debtPoolImpairmentApply',
            'templateUrl':'../../nrec_bcp_mdle/html/debtImpairment/bcp_impairment_guide.html'
        },
        {//现货动态 库存清单导入
            'state':'bsystasktab.stockListImportApply',
            'url':'/bsystasktab.stockListImportApply',
            'templateUrl':'../../sto_dmp_mdle/html/stockListImportApply/stockImport_guide.html'
        },
        {//应收类出池申请
            'state':'bsystasktab.NdebtOutPool',
            'url':'/bsystasktab.NdebtOutPool',
            'templateUrl':'../../nrec_bcp_mdle/html/buscont/debt_outPool_apply.html',
            'controller':'debtOutPoolApplyController'
        },
        {//应收类入池申请
            'state':'bsystasktab.NdebtInPool',
            'url':'/bsystasktab.NdebtInPool',
            'templateUrl':'../../nrec_bcp_mdle/html/buscont/debt_inPool_apply.html',
            'controller':'debtInPoolApplyController'
        }

    ];
    //模块的依赖加载配置
    var dependency=[
        //todo
    ];
    

    
    scubeUI.module('bsystaskModule',dependency,routeArry)
}());
