/**
 * @author 	mengjiajia
 * @version 1.0
 * @Copyright Shanghai Huateng Software Systems Co., Ltd.
 * Create at:   2016/11/21
 */
(function(){

	//跳转的路由配置
	var routeArry=[
		{
			'state':'list',
			'url':'/contlist',
			'default':'true',
			'templateUrl':'../html/buscont/bcp_cont_list.html',
			'controller':'nrBcpContListController'
		},
		{//国内信保保理
			'state':'credit',
			'url':'/contcredit',
			'default':'true',
			'templateUrl':'../html/buscont/creditFactoringConInfo.html',
			'controller':'nrBcpContEditController'
		},
		{//国内双保理
			'state':'double',
			'url':'/contdouble',
			'default':'true',
			'templateUrl':'../html/buscont/doublfactorContAdd.html',
			'controller':'nrBcpContEditController'
		},
		{//租赁保理
			'state':'lease',
			'url':'/contlease',
			'default':'true',
			'templateUrl':'../html/buscont/leasefactorContAdd.html',
			'controller':'nrBcpContEditController'
		},
		{//国内保理/反保理/应收账款质押/国内保理池/应收账款质押池/出口退税池
			'state':'local',
			'url':'/contlocal',
			'default':'true',
			'templateUrl':'../html/buscont/localfactorContAdd.html',
			'controller':'nrBcpContEditController'
		},
		{
			'state':'debt',
			'url':'/contdebt',
			'default':'true',
			'templateUrl':'../html/buscont/bcp_debt_manage.html',
			'controller':'DebtInfoManageController'
		},
		{
			'state':'debtedit',
			'url':'/contdebtedit',
			'default':'true',
			'templateUrl':'../html/debtmanage/bcp_debt_edit.html',
			'controller':'DebtInfoEditController'
		},
		{
			'state':'progress',
			'url':'/contprogress',
			'default':'true',
			'templateUrl':'../html/debtmanage/bcp_debt_progress_list.html',
			'controller':'DebtInfoProgressController'
		},

		{
			'state':'inPool',
			'url':'/inPool',
			'templateUrl':'../html/buscont/debt_inPool_apply.html',
			'controller':'debtInPoolApplyController'
		},
		{
			'state':'outPool',
			'url':'/outPool',
			'templateUrl':'../html/buscont/debt_outPool_apply.html',
			'controller':'debtOutPoolApplyController'
		},
		{
			'state':'inPoolApplyList',
			'url':'/inPoolApplyList',
			'templateUrl':'../html/buscont/inPool_apply_list.html',
			'controller':'InPoolAppplyListController'
		},
		{
			'state':'outPoolApplyList',
			'url':'/outPoolApplyList',
			'templateUrl':'../html/buscont/outPool_apply_list.html',
			'controller':'OutPoolAppplyListController'
		},
		{
			'state':'showProcess',
			'url':'/showProcess',
			'default':'true',
			'templateUrl':'../html/showProcess/showProcess.html',
			'controller':'showProcessController'
		}
	];
	//模块的依赖加载配置
	var dependency=[
		//todo
	];
	scubeUI.module('nrecBcpCont_mdle',dependency,routeArry);
}());
