INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0101', '净利润增长率1(%)', '111', '0', null, '(N3500[3]-A3500[3])*100/A3500[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0102', '销售收入增长率(%)', null, '0', null, '(N3111[3]-A3111[3])*100/A3111[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0103', '净利润增长率(%)', null, '0', null, '(N3500[3]-A3500[3])*100/A3500[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0104', '销售收入增长率(%)', null, '0', null, '(N3111[3]-A3111[3])*100/A3111[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0105', '净利润增长率(%)', null, '0', null, '(N3500[3]-A3500[3])*100/A3500[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0106', '销售收入增长率(%)', null, '0', null, '(N3111[3]-A3111[3])*100/A3111[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0201', '净资产收益率(%)', null, '0', null, 'N3500[3]*100*2/(A2431[3]+N2431[3])', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0202', '净资产收益率(%)', null, '0', null, 'N3500[3]*100*2/(A2431[3]+N2431[3])', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0203', '净资产收益率(%)', null, '0', null, 'N3500[3]*100*2*2/(A2431[3]+N2431[3])', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0401', '速动比率', null, '0', null, '(N1100[3]-N1171[3])*100/N2100[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0402', '速动比率', null, '0', null, '(N1100[3]-N1171[3])*100/N2100[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0403', '速动比率', null, '0', null, '(N1100[3]-N1171[3])*100/N2100[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0501', '流动比率', null, '0', null, 'N1100[3]*100/N2100[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0502', '流动比率', null, '0', null, 'N1100[3]*100/N2100[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0503', '流动比率', null, '0', null, 'N1100[3]*100/N2100[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0801', '总资产报酬率(%)', null, '0', null, 'N3400[3]*100*2/(A1000[3]+N1000[3]) ', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0802', '存货周转率(次)', null, '0', null, 'N3211[3]*2/(A1171[3]+N1171[3])', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0803', '应收帐款周转率(次)', null, '0', null, 'N3111[3]*2/(A1142[3]+N1142[3])', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0804', '资产负债率(%)', null, '0', null, 'N2300[3]*100/N1000[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0805', '现金流动负债比率', null, '0', null, 'N5127[3]*100/N2100[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0806', '总资产周转率(次)', null, '0', null, 'N3111[3]*2/(A1000[3]+N1000[3])', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0807', '利息保障倍数', null, '0', null, '(N3400[3]+N4315[3])/N4315[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0808', '总债务/EBITDA(%)', null, '0', null, 'N2300[3]*100/(N3500[3]+N1292[3]+N1243[3]+N1272[3]+N1291[3]+N4315[3])', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0809', '长期资产适合率(%)', null, '0', null, '(N2431[3]+N2200[3])*100/(N1242[3]+N1213[3]+N1222[3])', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0810', '运营毛利润率(%)', null, '0', null, '(N3111[3]-N3211[3]-N3214[3])*100/N3111[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0811', '后台费用率(%)', null, '0', null, '(N3215[3]+N3111[3])*100/N3215[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0812', '净利润率(%)', null, '0', null, 'N3500[3]*100/N3111[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0813', '资金运营周期(天)', null, '0', null, '360*((A1142[3]+N1142[3])/(N3111[3]*2)+(A1171[3]+N1171[3])/(N3211[3]*2)-(A2122[3]+N2122[3])/(N3211[3]*2))', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0814', '研发投入比', null, '0', null, 'N1281[3]/N3111[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0815', '带息负债比率(%)', null, '0', null, '(N2111[3]+N2134[3]+N2151[3]+N2211[3])*100/N2300[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0816', '资本积累率(%)', null, '0', null, '(N2431[3]-A2431[3])*100/A2431[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0817', '现金比率', null, '0', null, '(N1111[3]+N1131[3]+N1141[3])*100/N2100[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0818', '经营活动现金净流量/总债务', null, '0', null, 'N5127[3]/N2300[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0819', '经营活动现金净流量/短期债务', null, '0', null, 'N5127[3]/N2100[3]', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0820', '总资产报酬率(%)', null, '0', null, 'N3400[3]*100*2/(A1000[3]+N1000[3]) ', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0821', '存货周转率(次)', null, '0', null, 'N3211[3]*2/(A1171[3]+N1171[3])', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0822', '应收帐款周转率(次)', null, '0', null, 'N3111[3]*2/(A1142[3]+N1142[3])', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0823', '现金比率', null, '0', null, '(N1111[3]+N1131[3]+N1141[3])*100/N2100[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0824', '经营活动现金净流量/短期债务', null, '0', null, 'N5127[3]/N2100[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0825', '资产负债率(%)', null, '0', null, 'N2300[3]*100/N1000[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0826', '经营活动现金净流量/总债务', null, '0', null, 'N5127[3]/N2300[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0827', '现金流动负债比率', null, '0', null, 'N5127[3]*100/N2100[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0828', '长期资产适合率(%)', null, '0', null, '(N2431[3]+N2200[3])*100/(N1242[3]+N1213[3]+N1222[3])', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0829', '总资产周转率(次)', null, '0', null, 'N3111[3]*2/(A1000[3]+N1000[3])', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0830', '利息保障倍数', null, '0', null, '(N3400[3]+N4315[3])/N4315[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0831', '总债务/EBITDA(%)', null, '0', null, 'N2300[3]*100/(N3500[3]+N1292[3]+N1243[3]+N1272[3]+N1291[3]+N4315[3])', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0832', '运营毛利润率(%)', null, '0', null, '(N3111[3]-N3211[3]-N3214[3])*100/N3111[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0833', '后台费用率(%)', null, '0', null, '(N3215[3]+N3111[3])*100/N3215[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0834', '净利润率(%)', null, '0', null, 'N3500[3]*100/N3111[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0835', '资金运营周期(天)', null, '0', null, '360*((A1142[3]+N1142[3])/(N3111[3]*2)+(A1171[3]+N1171[3])/(N3211[3]*2)-(A2122[3]+N2122[3])/(N3211[3]*2))', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0837', '研发投入比', null, '0', null, 'N1281[3]/N3111[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0838', '带息负债比率(%)', null, '0', null, '(N2111[3]+N2134[3]+N2151[3]+N2211[3])*100/N2300[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0839', '资本积累率(%)', null, '0', null, '(N2431[3]-A2431[3])*100/A2431[3]', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0840', '总资产报酬率(%)', null, '0', null, 'N3400[3]*100*2*2/(A1000[3]+N1000[3]) ', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0841', '存货周转率(次)', null, '0', null, 'N3211[3]*2*2/(A1171[3]+N1171[3])', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0842', '应收帐款周转率(次)', null, '0', null, 'N3111[3]*2*2/(A1142[3]+N1142[3])', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0843', '现金比率', null, '0', null, '(N1111[3]+N1131[3]+N1141[3])*100/N2100[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0844', '经营活动现金净流量/短期债务', null, '0', null, 'N5127[3]/N2100[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0845', '资产负债率(%)', null, '0', null, 'N2300[3]*100/N1000[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0846', '经营活动现金净流量/总债务', null, '0', null, 'N5127[3]/N2300[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0847', '现金流动负债比率', null, '0', null, 'N5127[3]*100*2/N2100[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0848', '长期资产适合率(%)', null, '0', null, '(N2431[3]+N2200[3])*100/(N1242[3]+N1213[3]+N1222[3])', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0849', '总资产周转率(次)', null, '0', null, 'N3111[3]*2*2/(A1000[3]+N1000[3])', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0850', '利息保障倍数', null, '0', null, '(N3400[3]+N4315[3])/N4315[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0851', '总债务/EBITDA(%)', null, '0', null, 'N2300[3]*100*2/(N3500[3]+N1292[3]+N1243[3]+N1272[3]+N1291[3]+N4315[3])', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0852', '运营毛利润率(%)', null, '0', null, '(N3111[3]-N3211[3]-N3214[3])*100/N3111[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0853', '后台费用率(%)', null, '0', null, '(N3215[3]+N3111[3])*100/N3215[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0854', '净利润率(%)', null, '0', null, 'N3500[3]*100/N3111[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0855', '资金运营周期(天)', null, '0', null, '360*((A1142[3]+N1142[3])/(N3111[3]*2)+(A1171[3]+N1171[3])/(N3211[3]*2)-(A2122[3]+N2122[3])/(N3211[3]*2)*2)', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0856', '研发投入比', null, '0', null, 'N1281[3]/N3111[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0857', '带息负债比率(%)', null, '0', null, '(N2111[3]+N2134[3]+N2151[3]+N2211[3])*100/N2300[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0858', '资本积累率(%)', null, '0', null, '(N2431[3]-A2431[3])*100/A2431[3]', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0901', '总计', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0902', '营运资金', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0903', '长期偿债能力', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0904', '权益乘数', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0905', '负债与所有者权益比', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0906', '负债与有形资产比', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0907', '总计', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0908', '流动资产周转率', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0909', '固定资产周转率', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0910', '应付账款周转率', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0911', '预付账款周转率', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0912', '预收账款周转率', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0913', '总计', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0914', '销售额现金比', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0915', '总资产增长率', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0916', '总计', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0917', '经营现金利息偿还能力', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB0918', '总计', '', '0', null, '', '01');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1001', '总计', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1002', '营运资金', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1003', '长期偿债能力', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1004', '权益乘数', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1005', '负债与所有者权益比', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1006', '负债与有形资产比', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1007', '总计', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1008', '流动资产周转率', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1009', '固定资产周转率', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1010', '应付账款周转率', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1011', '预付账款周转率', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1012', '预收账款周转率', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1013', '总计', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1014', '销售额现金比', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1015', '总资产增长率', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1016', '总计', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1017', '经营现金利息偿还能力', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1018', '总计', '', '', null, '', '03');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1101', '总计', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1102', '营运资金', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1103', '长期偿债能力', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1104', '权益乘数', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1105', '负债与所有者权益比', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1106', '负债与有形资产比', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1107', '总计', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1108', '流动资产周转率', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1109', '固定资产周转率', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1110', '应付账款周转率', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1111', '预付账款周转率', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1112', '预收账款周转率', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1113', '总计', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1114', '销售额现金比', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1115', '总资产增长率', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1116', '总计', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1117', '经营现金利息偿还能力', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('CWZB1118', '总计', '', '', null, '', '04');
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0061', '经营能力', null, '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0062', '偿债能力', null, '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0063', '运营能力', null, '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0064', '发展能力', null, '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0065', '现金流', null, '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0066', '集团财务指标测试测试', null, '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0068', '2', '2', '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0069', '333', '财报333', '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SUBJ0072', '2222', '2', '0', null, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3100', '一、营业收入', null, '0', 1, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3111', '其中:主营业务收入', null, '0', 2, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3112', '　　　其他业务收入', null, '0', 3, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3200', '二、营业成本', null, '0', 4, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3211', '其中:主营业务成本', null, '0', 5, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3212', '　　　其他业务支出', null, '0', 6, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3213', '　减:营业税金及附加', null, '0', 7, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3214', '　减:销售费用', null, '0', 8, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3215', '　　　管理费用', null, '0', 9, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3216', '　　　财务费用', null, '0', 10, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3221', '　　　资产减值损失', null, '0', 11, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3222', '　加:公允价值变动收益（损失以“-”填列）', null, '0', 12, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3223', '　加:投资收益（亏损以“-”填列）', null, '0', 13, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3224', '　　　其中:对联营企业的投资收益', null, '0', 14, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3225', '　　　　　对合营企业的投资收益', null, '0', 15, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3300', '三、营业利润（亏损以“-”填列）', null, '0', 16, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3331', '　加: 营业外收入', null, '0', 17, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3332', '　减: 营业外支出', null, '0', 18, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3333', '　　　其中:非流动资产处置损失', null, '0', 19, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3400', '四、利润总额（亏损总额以“-”填列）', null, '0', 20, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3411', '　减:所得税费用', null, '0', 21, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3500', '五、净利润（净亏损以“-”填列）', null, '0', 22, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3501', '　归属于母公司所有者的净利润', null, '0', 23, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3502', '　少数股东损益', null, '0', 24, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3600', '六、每股收益', null, '0', 25, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3601', '　（一）基本每股收益', null, '0', 26, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('SYB3602', '　（二）稀释每股收益', null, '0', 27, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL1198', null, null, '0', 78, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4100', '一、经营活动产生的现金流量：', null, '0', 1, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4111', '　销售商品、提供劳务收到的现金', null, '0', 2, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4112', '　收到的税费返还', null, '0', 3, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4113', '　收到的其他与经营活动有关的现金', null, '0', 4, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4114', '　　　经营活动现金流入小计', null, '0', 5, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4121', '　购买商品、接受劳务支付的现金', null, '0', 6, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4122', '　支付给职工以及为职工支付的现金', null, '0', 7, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4123', '　支付的各项税费', null, '0', 8, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4124', '　支付的其它与经营活动有关现金', null, '0', 9, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4125', '　　　经营活动现金流出小计', null, '0', 10, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4126', '　　经营活动产生的现金流量净额', null, '0', 11, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4200', '二、投资活动产生的现金流量：', null, '0', 12, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4211', '　收回投资所收到的现金', null, '0', 13, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4212', '　　其中：收回转让给集团外公司（集团外关联方和非关联方）的投资所收到的现金', null, '0', 14, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4213', '	　取得投资收益所收到的现金', null, '0', 15, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4214', '　　其中：从集团外公司（集团外关联方和非关联方）取得的投资收益所收到的现金', null, '0', 16, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4215', '　处置固定资产、无形资产和其他长期资产收回的现金净额', null, '0', 17, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4216', '　处置子公司及其他营业单位收到的现金净额', null, '0', 18, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4217', '　收到的其他与投资活动有关的现金', null, '0', 19, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4218', '　　　投资活动现金流入小计', null, '0', 20, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4221', '　购建固定资产、无形资产和其他长期资产所支付的现金', null, '0', 21, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4222', '　投资所支付的现金', null, '0', 22, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4223', '　　其中：投资集团外公司（集团外关联方和非关联方）所支付的现金', null, '0', 23, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4224', '　取得子公司及其他营业单位支付的现金净额', null, '0', 24, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4225', '　支付的其他与投资活动有关的现金', null, '0', 25, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4227', '　　　投资活动现金流出小计', null, '0', 26, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4228', '　　投资活动产生的现金流量净额', null, '0', 27, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4300', '三、筹资活动产生的现金流量：', null, '0', 28, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4301', '　吸收投资所收到的现金', null, '0', 29, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4302', '　　其中：吸收集团外公司（集团外关联方和非关联方）投资所收到的现金', null, '0', 30, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4303', '　取得借款收到的现金', null, '0', 31, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4304', '　　其中：从集团外公司（集团外关联方和非关联方）借款所收到的现金', null, '0', 32, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4305', '　发行债券收到的现金', null, '0', 33, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4306', '　收到的其他与筹资活动有关的现金', null, '0', 34, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4307', '　　　筹资活动现金流入小计', null, '0', 35, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4311', '　偿还债务所支付的现金', null, '0', 36, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4312', '　　其中：偿还集团外公司（集团外关联方和非关联方）债务所支付的现金', null, '0', 37, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4313', '　分配股利、利润和偿付利息所支付的现金', null, '0', 38, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4314', '　　其中：支付给集团外公司（集团外关联方和非关联方）的股利、利润', null, '0', 39, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4315', '　　其中：支付给集团外公司（集团外关联方和非关联方）的利息', null, '0', 40, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4316', '　支付的其他与筹资活动有关的现金', null, '0', 41, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4317', '　　　筹资活动现金流出小计', null, '0', 42, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4318', '　　筹资活动产生的现金流量净额', null, '0', 43, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4400', '四、汇率变动对现金的影响额', null, '0', 44, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4500', '五、现金及现金等价物净增加额', null, '0', 45, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4501', '加：期初现金及现金等价物余额', null, '0', 46, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL4600', '六、期末现金及现金等价物余额', null, '0', 47, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5100', '1.将净利润调节为经营活动的现金流量：', null, '0', 50, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5111', '　　净利润', null, '0', 51, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5112', '　　　加：资产减值准备', null, '0', 52, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5113', '　　固定资产折旧、油气资产折耗、生产性生物资产折旧', null, '0', 53, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5114', '　　无形资产摊销', null, '0', 54, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5115', '　　长期待摊费用摊销', null, '0', 55, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5116', '　　处置固定资产、无形资产和其他长期资产的损失（收益以“－”号填列）', null, '0', 56, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5117', '　　固定资产报废损失（收益以“－”号填列）', null, '0', 57, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5118', '　　公允价值变动损失（收益以“－”号填列）', null, '0', 58, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5119', '　　财务费用（收益以“－”号填列）', null, '0', 59, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5120', '　　投资损失（收益以“－”号填列）', null, '0', 60, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5121', '　递延所得税资产减少（增加以“－”号填列）', null, '0', 61, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5122', '　递延所得税负债增加（减少以“－”号填列）', null, '0', 62, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5123', '　存货的减少（增加以“－”号填列）', null, '0', 63, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5124', '　经营性应收项目的减少（增加以“－”号填列）', null, '0', 64, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5125', '　经营性应付项目的增加（减少以“－”号填列）', null, '0', 65, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5126', '　其他', null, '0', 66, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5127', '　经营活动产生的现金流量净额', null, '0', 67, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5200', '2.不涉及现金收支的投资和筹资活动：', null, '0', 68, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5201', '　　债务转为资本', null, '0', 69, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5202', '　　一年内到期的可转换公司债券', null, '0', 70, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5203', '　　融资租入固定资产', null, '0', 71, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5300', '3.现金及现金等价物净增加情况：', null, '0', 72, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5301', '　现金的期末余额', null, '0', 73, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5302', '　减：现金的期初余额', null, '0', 74, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5303', '　加：现金等价物的期末余额', null, '0', 75, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5304', '　减：现金等价物的期初余额', null, '0', 76, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5404', '　现金及现金等价物净增加额', null, '0', 77, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL5999', '补充资料', null, '0', 49, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6100', '一、现金', null, '0', 79, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6101', '　其中：库存现金', null, '0', 80, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6102', '　　可随时用于支付的银行存款', null, '0', 81, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6103', '　　可随时用于支付的其他货币资金', null, '0', 82, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6104', '　　可用于支付的存放中央银行款项', null, '0', 83, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6105', '　　存放同业款项', null, '0', 84, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6106', '　　拆放同业款项', null, '0', 85, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6200', '二、现金等价物', null, '0', 86, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6201', '　其中：三个月内到期的债券投资', null, '0', 87, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6300', '三、银行透支（以负数填列）', null, '0', 88, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6400', '四、期末现金及现金等价物余额', null, '0', 89, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('XJLL6401', '　其中：母公司或集团内子公司使用受限制的现金和现金等价物', null, '0', 90, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1000', '资产总计', null, '0', 57, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1100', '流动资产合计', null, '0', 23, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1111', '　货币资金', null, '0', 2, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1121', '　拆出资金', null, '0', 4, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1131', '　交易性金融资产', null, '0', 5, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1141', '　应收票据', null, '0', 6, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1142', '　应收账款', null, '0', 7, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1143', '　　减：应收账款坏账准备', null, '0', 8, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1144', '　应收账款净额', null, '0', 9, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1151', '　保理应收账款', null, '0', 10, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1152', '　预付款项', null, '0', 11, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1153', '　应收利息', null, '0', 12, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1154', '　应收股利', null, '0', 13, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1161', '　其他应收款', null, '0', 14, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1162', '　　减：其他应收款坏账准备', null, '0', 15, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1163', '　其他应收款净额', null, '0', 16, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1164', '　买入返售金融资产', null, '0', 17, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1171', '　存货', null, '0', 18, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1172', '　　减：存货跌价准备', null, '0', 19, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1173', '　存货净额', null, '0', 20, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1181', '　一年内到期的非流动资产', null, '0', 21, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1191', '　其他流动资产', null, '0', 22, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1198', null, null, '0', 113, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1199', '流动资产：', null, '0', 1, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1200', '非流动资产合计', null, '0', 56, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1211', '　发放贷款及垫款', null, '0', 26, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1212', '　可供出售金融资产', null, '0', 27, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1213', '　持有至到期投资', null, '0', 28, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1214', '　　减:持有至到期投资减值准备', null, '0', 29, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1215', '　持有至到期投资净额', null, '0', 30, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1221', '　长期应收款', null, '0', 31, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1222', '　长期股权投资', null, '0', 32, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1223', '　　减：长期股权投资减值准备', null, '0', 33, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1224', '　长期股权投资净额', null, '0', 34, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1241', '　投资性房地产', null, '0', 35, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1242', '　固定资产', null, '0', 36, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1243', '　　减：累计折旧', null, '0', 37, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1244', '　　减：固定资产减值准备', null, '0', 38, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1245', '　固定资产净额', null, '0', 39, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1251', '　在建工程', null, '0', 40, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1252', '　　减：在建工程减值准备', null, '0', 41, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1253', '　在建工程净额', null, '0', 42, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1261', '　工程物资', null, '0', 43, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1262', '　固定资产清理', null, '0', 44, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1271', '　无形资产', null, '0', 45, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1272', '　　减：累计摊销', null, '0', 46, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1273', '　　减：无形资产减值准备', null, '0', 47, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1274', '　无形资产净额', null, '0', 48, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1281', '　开发支出', null, '0', 49, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1282', '　商誉', null, '0', 50, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1283', '　　减:商誉减值准备', null, '0', 51, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1284', '　商誉净额', null, '0', 52, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1291', '　长期待摊费用', null, '0', 53, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1292', '　递延所得税资产', null, '0', 54, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1293', '　其他非流动资产', null, '0', 55, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ1299', '非流动资产：', null, '0', 25, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2100', '流动负债合计', null, '0', 80, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2111', '　短期借款', null, '0', 59, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2112', '　保理借款', null, '0', 60, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2113', '　向中央银行借款', null, '0', 61, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2114', '　吸收存款及同业存放', null, '0', 62, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2115', '　拆入资金', null, '0', 63, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2116', '　交易性金融负债', null, '0', 64, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2121', '　应付票据', null, '0', 65, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2122', '　应付账款', null, '0', 66, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2123', '　预收款项', null, '0', 67, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2124', '　卖出回购金融资产款', null, '0', 68, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2131', '　应付短期融资券', null, '0', 69, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2132', '　应付职工薪酬', null, '0', 70, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2133', '　应交税费', null, '0', 71, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2134', '　应付利息', null, '0', 72, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2135', '　应付股利', null, '0', 73, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2141', '　其他应付款', null, '0', 74, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2151', '　一年内到期的非流动负债', null, '0', 78, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2161', '　其他流动负债', null, '0', 79, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2199', '流动负债：', null, '0', 58, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2200', '非流动负债合计', null, '0', 93, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2211', '　长期借款', null, '0', 83, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2212', '　应付债券', null, '0', 84, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2213', '　长期应付款', null, '0', 85, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2214', '　专项应付款', null, '0', 86, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2215', '　预计负债', null, '0', 87, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2216', '　递延所得税负债', null, '0', 88, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2221', '　其他非流动负债', null, '0', 91, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2299', '非流动负债：', null, '0', 82, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2300', '负债合计', null, '0', 95, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2400', '负债和所有者(或股东)权益总计', null, '0', 114, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2411', '　实收资本（或股本）', null, '0', 99, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2412', '　资本公积', null, '0', 100, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2413', '　　减：库存股', null, '0', 101, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2414', '　盈余公积', null, '0', 102, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2415', '　一般风险准备', null, '0', 103, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2416', '　未分配利润', null, '0', 104, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2417', '　外币报表折算差额', null, '0', 106, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2418', '　归属于母公司所有者权益', null, '0', 108, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2421', '　少数股东权益', null, '0', 110, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2431', '　所有者权益合计', null, '0', 112, null, null);
INSERT INTO b_fin_cnfg_subj (SUBJ_ID, SUBJ_NM, REM, DEL_FLG, ROW_NUMBER, INDEX_EXPRESS, RP_SOURCE) VALUES ('ZCFZ2499', '所有者权益（或股东权益）：', null, '0', 97, null, null);
